{{- if eq .Values.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kanbanboard.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "kanbanboard.fullname" . }}
  port:
    targetPort: http
  tls:
    termination: edge
{{- end }}
